language: node_js
node_js:
    - 'stable'
    - '8'
    - '6'

before_script:
  - node util/getBlast.js
  - npm install -g typescript --save-dev
  - npm run build
  - npm uninstall typescript

script:
  - npm test

branches:
  only:
    - master

install:
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1
