language: node_js
node_js:
    - 'stable'
    - '8'
    - '6'
sudo: true

before_script:
  - npm install -g typescript --save-dev
  - npm run build
  - npm uninstall typescript
  - npm test

script:


branches:
  only:
    - master

install:
  - npm install
  - node util/getBlast.js


cache:
  directories:
    - node_modules

git:
  depth: 1
